# We must configure build-std to recompile core and compiler_builtins
# This allows recompilation of libs instead of precompiled versions
# Also added compiler-builtins-mem to enable memory-related functions
# such ass memcmp memset memcpy
# manually configuring json target spec as target to avoid the target argument
[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins"]
[build]
target = "x86_64-rustless_os.json"
